version: '3.8'

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: complexbedb
      POSTGRES_USER: gaurisariag
      POSTGRES_PASSWORD: gaurisariag
    ports:
      - "5432:5432"
    volumes:
      - pg18data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://gaurisariag:gaurisariag@postgres:5432/complexbedb"
    depends_on:
      - postgres

volumes:
  pg18data:
